### PR TITLE
Restore attribution

### PR DESCRIPTION
**Pull request by fabianegli**
My last PR #51 changed the attribution in some cases. Hence I reverted the merge of the GH Action files which restores the original attribution logic.

The work is still done with the Python. This PR does not revert to PHP.

In line with the current behaviour and contrary to pre PR #51 the main GH Action is triggered by every push to main.

--

A bit off topic is the addition of the file encoding to the tests. I believe this makes sense.

--

Update the PR link.

### CODE REVIEW

**Review by glyn — COMMENTED** [review]
I can't easily verify that this PR will correctly attribute all changes.

Would it be possible to add tests to verify correct attribution?

**Comment by fabianegli** [comment]
These are the diffs to before #51

```diff
% diff main-old.yml main-this-PR.yml 
10a11,12
>     branches:
>       - "main"
25,26c27,28
<           echo "Running update script ..."
<           php -f code/action.php
---
>           echo "Updating robots.txt and table-of-bot-metrics.md if necessary ..."
>           python code/dark_visitors.py --convert
```

```diff
diff daily_update.yml ai-robots-txt/ai.robots.txt/.github/workflows/ai_robots_update.yml 
1c1
< name: Daily Update from Dark Visitors
---
> name: Updates for AI robots files
18,19c18,19
<           echo "Running update script ..."
<           python code/dark_visitors.py
---
>           echo "Updating robots.json with data from darkvisitor.com ..."
>           python code/dark_visitors.py --update
23c23
<           git diff --quiet && git diff --staged --quiet || (git commit -m "Daily update from Dark Visitors" && git push)
---
>           git diff --quiet && git diff --staged --quiet || (git commit -m "Update from Dark Visitors" && git push)
30c30
<       message: "Daily update from Dark Visitors"
---
>       message: "Update from Dark Visitors"
```

**Comment by fabianegli** [comment]
The problem I saw was that updates from dark visitors were correctly attributed in the json file, but that attribution did not propagate to the robots.txt file as seen in the consecutive commits [37065f9 "Update from Dark Visitors"](https://github.com/ai-robots-txt/ai.robots.txt/commit/37065f911805370426a9a33b1af5f400b24a0c16) and [609ddca "Updated from new robots.json"](https://github.com/ai-robots-txt/ai.robots.txt/commit/609ddca39295d1ec8ec47bc4c1c609135bc238d3) compared to earlier where https://github.com/ai-robots-txt/ai.robots.txt/commit/7851cea4fd4e233cd7ed74e48c3316d114e29f3b was followed by https://github.com/ai-robots-txt/ai.robots.txt/commit/632e9d65109584c2ed12ecf2f4a898e9a276e604 where both carried the commit message "Daily update from Dark Visitors".

**Comment by fabianegli** [comment]
@glyn I hope the diff in combination with the elaboration on the observed behaviour before and after #51 was merged make the changes easier to understand. While I would also appreciate a test, I honestly don't know how to reasonably test for GH Actions. I briefly thought I could remove one entry form the dark visitors list and see it being reapplied to the PR, but that would change the added by timestamp, would it not?

**Comment by glyn** [comment]
> @glyn I hope the diff in combination with the elaboration on the observed behaviour before and after #51 was merged make the changes easier to understand.

That helped a bit. The thing I struggle with is that it appears a push to main will also fold in changes from dark visitors. Right?

> While I would also appreciate a test, I honestly don't know how to reasonably test for GH Actions. I briefly thought I could remove one entry form the dark visitors list and see it being reapplied to the PR, but that would change the added by timestamp, would it not?

I would have thought the testing approach would be to separate out a core of the Python code as some function(s) called from the github actions and with the various files as input parameters and with outputs of the generated files and attribution data. Tests could then pass in test versions of robots.json and/or the dark visitors file and check the results. (Sorry my Python knowledge/envuironment isn't up to doing this.)

**Comment by fabianegli** [comment]
The tests are currently not run automatically for each PR/update. This PR does not change that, I'd like to address that in a separate PR. To make this PR purely about the GH Actions I reverted the commit adding changes to test files.

> [...] it appears a push to main [...]

The current GH Actions do so, too. The following code chunk only means that the GH action is triggered by changes to the main branch, like it is the case when the json is manually updated.

**Comment by fabianegli** [comment]
What do you mean by "appears a push to main will also fold in changes from dark visitors."? Don't you expect all changes to end up in main?

The way the script works is that it only pulls updates from Dark Visitors if it is invoked with the --update flag, otherwise it will skip the update. The main GH Action only pulls changes form json to txt and only the ai_robots_update Action updates the json based on the Dark Visitors website.

**Comment by glyn** [comment]
> What do you mean by "appears a push to main will also fold in changes from dark visitors."? Don't you expect all changes to end up in main?

Yes, but I don't expect dark visitors to be consulted on every merge to main.

> 
> The way the script works is that it only pulls updates from Dark Visitors if it is invoked with the --update flag, if it is invoked with the --convert flag it will skip the update. The main GH Action only applies changes it robots.json to robots.txt. The ai_robots_update Action updates the robots.json based on the Dark Visitors website and then triggers main which then uses the commit message indicating a change from Dark Visitors for the commit after converting the updated robots.json to robots.txt.

Ah, I'd missed that. I'm now much happier. Thanks.

**Review by glyn — APPROVED** [review]

**Pull request merged**
